# test
# book_photos = [
#     'AgACAgIAAxkBAAIZnmR6z7u1vttz49LMzsAM8T5lVzUfAAJnxTEbHBjQSyUqHRHlNnZQAQADAgADeQADLwQ',
#     'AgACAgIAAxkBAAIZpWR6z-2-6WlzhqSMR74zRBK5HfhBAAJoxTEbHBjQS-RI7mWlDwKaAQADAgADeQADLwQ',
#     'AgACAgIAAxkBAAIZ82R61cJeHjz3TuLh4ZMTxGycm44NAAKAxzEbwVTZS0wSBbC8HbFRAQADAgADeQADLwQ',
#     'AgACAgIAAxkBAAIZ-mR61fHT2lr46AMNsR9fML0IXRtrAAKBxzEbwVTZSyolf8_ixogNAQADAgADeQADLwQ'
# ]

# prod
book_photos = [
    'AgACAgIAAxkBAAIzcmR63y1etkyBSzDstFpEZ2jCjQ46AAJnxTEbHBjQS0IVkLICMY52AQADAgADeQADLwQ',
    'AgACAgIAAxkBAAIzeWR63z-iOBR7o_pFQEftnq27psgNAAJoxTEbHBjQS088K4anrHg3AQADAgADeQADLwQ',
    'AgACAgIAAxkBAAIzgGR631jnO-mcgNoWWA6HJ_6SYwVIAAKAxzEbwVTZSzR0hprRaFGQAQADAgADeQADLwQ',
    'AgACAgIAAxkBAAIzh2R632oEcRaD2hbux_lnKV8QiyTTAAKBxzEbwVTZSw7IQ5bVlCKhAQADAgADeQADLwQ'
]