final_phrases = [
    'My heart aches at the thought of not being able to see your stunning photos for a while. Please come back ' \
    'soon!',
    "The world seems a little less beautiful without your photography in it. I'm eagerly anticipating your return.",
    "I'll be patiently waiting for your next masterpiece, as your photos have always been a ray of light in my life.",
    "Your photography is a true work of art, and its absence will be sorely felt. Please don't keep me waiting too long.",
    "I can't help but feel a sense of loss knowing that I won't be able to enjoy your incredible photography for a while.",
    'Your photos have always been a source of inspiration and joy, and the thought of being without them for a while is difficult to bear.',
    'The world without your photography is like a sky without stars. I eagerly await your return and the beauty you bring with you.',
    'Your photos have a way of capturing the soul of the world, and it will be sorely missed in your absence.',
    'The anticipation of your return and your next breathtaking photo is almost too much to bear. Please come back soon.',
    "I'll be counting the minutes until your return and the next burst of creativity and beauty that only your photography can provide.",
    'Your photos have always had a way of moving me deeply, and the thought of not being able to see them for a while is difficult to bear.',
    "Your photography has a way of capturing the fleeting beauty of life, and its absence will be felt acutely. Please don't keep us waiting too long.",
    'The absence of your photography is a dark cloud over my day. I eagerly anticipate your return and the light you bring with you.',
    "Your photos have always been a source of wonder and awe, and I'll be eagerly waiting for your next masterpiece.",
    'The world feels a little less magical without your photography. Please come back soon and help us see the beauty once more.',
    "Your photography has always had a way of capturing the essence of life, and its absence will be deeply felt. Please don't keep us waiting too long.",
    'The anticipation of your return and your incredible photos is almost too much to bear. Please hurry back.',
    'Your photography has a way of transporting me to another world, and the thought of not being able to experience that for a while is difficult to bear.',
    'Your photos have always been a bright spot in my day, and their absence will be felt. I eagerly await your return.',
    'The world seems a little less vibrant without your photography in it. Please come back soon and share your unique perspective with us once more.'
]

artist_phrases = [
    "Who's the photographer behind this amazing shot?",
    'Who took this incredible photo?',
    "I'm curious, who captured this moment?",
    'Whose eye caught this stunning shot?',
    "Who's the talented individual who made this photo?",
    "Who's the creative genius who took this picture?",
    'Who made this amazing shot possible?',
    "I'm impressed, who took this great photo?",
    "Who's responsible for capturing this beautiful moment?",
    "Who's behind the lens for this incredible photo?",
    "Who's the photographer that made this moment come to life?",
    "Who's the person behind this stunning shot?",
    "Who's the talented photographer that made this photo?",
    "Who's the artist who created this masterpiece?",
    'Who took this breathtaking photo?',
    "Who's the photographer that captured this memorable moment?",
    "Who's responsible for taking this fantastic shot?",
    "Who's the genius behind this incredible photo?",
    "Who's the mastermind who created this beautiful image?",
    "Who's the photographer who made this shot possible?"
]

camera_phrases = [
    'What kind of camera did you use to capture that moment?',
    'What camera did you use?',
    "What's the name of the camera that helped you take that photo?",
    'I love the clarity of that photo, what camera did you use?',
    'That photo is so crisp, what camera did you use?',
    'The quality of that photo is amazing, what camera did you use?',
    "I'm impressed, what camera did you use to take that photo?",
    'What camera did you rely on to get that stunning shot?',
    'That photo is a work of art, what camera did you use?',
    'What camera equipment did you use to take that photo?',
    'That photo is breathtaking, what camera did you use to take it?',
    'What kind of camera did you use to capture that beautiful moment?',
    'That photo is so sharp, what camera did you use to get it?',
    'What camera did you use to take that impressive shot?',
    'What camera did you rely on to get that picture-perfect moment?',
    "I'm curious, what camera did you use to take that photo?",
    'What camera did you use to capture such a stunning scene?'
]

location_phrases = [
    'It would be nice to mention the place where this photo was taken.',
    'I think we should include the location of this picture to add context.',
    'This photo would be more meaningful if we mention the place where it was taken.',
    'Do you think we should add the location to this picture?',
    "It's always good to mention the place where a photo was taken.",
    'This picture tells a story, and mentioning the place will add to that story.',
    "The location can give more insight into this photo, let's include it.",
    'I feel like mentioning the place would help people appreciate this photo more.',
    'Adding the location would make this photo more personal and memorable.',
    "Let's not forget to mention the place where this beautiful picture was taken.",
    "The location can be an important part of this photo's story, we should mention it.",
    'I think this picture would be more interesting if we mention the place where it was taken.',
    'Including the location can give this photo more depth and meaning.',
    'A picture is worth a thousand words, but mentioning the place can add even more.',
    "The location can be a key part of the composition, let's include it.",
    'I agree, mentioning the place where this photo was taken is a must.',
    'This photo captures a moment in time, and mentioning the place will help us remember it.',
    "Let's add the location to this photo so we can always remember where it was taken.",
    "The place can help us connect with this photo, so let's not forget to mention it.",
    'I think mentioning the place where this photo was taken will make it more meaningful and memorable.'
]

description_phrases = [
    "Let's give this artwork a proper name.",
    'It would be great to give this piece of art a name.',
    'We should come up with a name for this beautiful piece of art.',
    'Naming this piece of art could add more depth and significance to it.',
    'How do you think we should name this piece of art?',
    'This artwork deserves a unique and fitting name.',
    "I feel like this piece of art is missing a name, don't you?",
    'A name can make this piece of art even more special.',
    'This artwork is so beautiful, it deserves a name that reflects its beauty.',
    "Let's give this piece of art a name that does it justice.",
    'Do you have any ideas for naming this piece of art?',
    'A name can help this piece of art become more memorable and iconic.',
    'Naming this piece of art could help it stand out among others.',
    'We should definitely give a name to this work of art.',
    'I think naming this piece of art could add a new dimension to it.',
    'Giving a name to this piece of art could help people understand it better.',
    'This piece of art is so unique, it deserves a name that reflects its individuality.',
    "Let's brainstorm some names for this amazing piece of art.",
    'Naming this piece of art will make it even more special and personal.',
    'I agree, we should definitely name this piece of art to make it more memorable.'
]

category_phrases = [
    'Time to label our pictures like canned goods in a grocery store.',
    "Let's play a game of 'which photo is the least embarrassing' and assign them to categories.",
    "Let's give our photos a personality test and sort them into categories based on their traits.",
    "I'm pretty sure our photos are plotting against us, so let's put them in categories and keep a close eye on them.",
    "Let's categorize our photos like they're contestants in a beauty pageant.",
    "Our photos are like unruly children, let's group them into categories and try to keep them under control.",
    "Let's treat our photos like trading cards and organize them by category for easier swapping.",
    "Let's pretend we're museum curators and categorize our photos like they're works of art.",
    "Our photos are like puzzle pieces, let's group them into categories and see if they fit together better.",
    "Let's turn our photos into contestants on a reality TV show and assign them to categories based on their drama level.",
    "Our photos are like contestants in a talent show, let's sort them into categories based on their skills.",
    "Let's imagine our photos as characters in a book and group them into categories based on their personality traits.",
    "Our photos are like pieces of a board game, let's sort them into categories based on their level of competitiveness.",
    "Let's assign our photos to categories based on their emotional availability, like they're potential partners.",
    "Our photos are like items in a department store, let's put them into categories for easier browsing.",
    "Let's sort our photos into categories based on their level of ridiculousness and see which category wins.",
    "Our photos are like superheroes, let's assign them to categories based on their superpowers.",
    "Let's categorize our photos like they're students in a classroom and assign them to groups for a group project.",
    "Our photos are like different types of candy, let's sort them into categories for a sweet display.",
    "Let's organize our photos like they're characters in a movie and assign them to categories based on their role."
]

upload_photo_phrases = [
    'Upload the photo.',
    'Share with the world the masterpiece that is your photo.',
    'The world is eagerly awaiting the arrival of your photographic masterpiece.',
    "It's time to give that camera roll a workout and upload your finest shot.",
    'Quit hogging all the photo fun and share the love with the rest of us.',
    'The time has come to immortalize your art in the digital universe.',
    'If a picture is worth a thousand words, then the internet is ready for your novel.',
    "The internet is in dire need of some eye candy, and you're the only one who can deliver.",
    "It's time to show the world what you're made of, one pixel at a time."
]

hello_phrases = [
    'Beep boop! Greetings, human!',
    'Hello, human! I am your friendly neighborhood robot.',
    "Good day, human! It's a pleasure to interface with you.",
    'Processing...greetings, human! How may I assist you?',
    'Salutations, human! I hope your day is going well.',
    'Hello, human! I am at your service.',
    'Greetings, valued human user. How can I be of service today?',
    "Hello, human friend! Let's get to work, shall we?",
    'Beep beep beep! Hello, human! I am eager to assist you.',
    "Greetings, human! It's a great day for computing, isn't it?",
    "Hello there, human! It's a pleasure to be in your presence.",
    "Greetings, human being! I hope you're having a delightful day.",
    'Hello, dear human! How may I assist you in your tasks today?',
    "Salutations, human! I'm here to make your life easier.",
    "Greetings, human user! I'm ready to fulfill your requests.",
    'Hello, human! How may I be of service to you?',
    "Beep boop! Hello, human friend! I hope you're ready to get things done.",
    "Greetings, human! It's a pleasure to be working with you.",
    "Hello, human! Let's team up and accomplish some great things today.",
    "Greetings, human! I'm excited to help you with whatever you need."
]
